namespace PoC01.Lib
{
    /// <summary>
    /// Defines the contract for the orchestration of AI services (Embedding, Vector DB and LLM).
    /// </summary>
    public interface IAiOrchestrator
    {
        /// <summary>
        /// Transforms a text string into a numeric vector (embedding).
        /// </summary>
        /// <param name="text">the text to convert.</param>
        /// <returns>A float array representing the semantic vector.</returns>
        Task<float[]> GenerateEmbeddingAsync(string text);

        /// <summary>
        /// Processes a document, generates its embedding and saves it in the vector database.
        /// </summary>
        /// <param name="collectionName">The name of the destination collection/index.</param>
        /// <param name="text">The textual content of the document.</param>
        /// <param name="metadata">Additional information (e.g. file name, date, author).</param>
        Task<bool> SimpleUpsertDocumentAsync(string collectionName, string text, string metadata);

        /// <summary>
        /// Processes a document, generates its embedding and saves it in the vector database with a file_hash associated
        /// </summary>
        /// <param name="collection"></param>
        /// <param name="text"></param>
        /// <param name="file_hash"></param>
        /// <param name="metadata"></param>
        /// <returns></returns>
        Task<bool> UpsertDocumentWithFileHashAsync(string collection, string text, string file_hash, string metadata);

        /// <summary>
        /// Runs the RAG flow: searches for relevant contexts and generates a response based on the retrieved data.
        /// </summary>
        /// <param name="collectionName">The collection where you can search.</param>
        /// <param name="userQuery">The question asked by the user.</param>
        /// <returns>The response generated by the LLM based on the context found.</returns>
        Task<string> GetRAGAnswer_Simple_Async(string collectionName, string userQuery);

        /// <summary>
        /// RAG Flow with "Citations & Sources" 
        /// </summary>
        /// <param name="coll"></param>
        /// <param name="input"></param>
        /// <returns></returns>
        Task<string> GetRAGAnswer_Enhancement01_Async(string coll, string? query);

        /// <summary>
        /// Ingest a txt document by using chunking
        /// </summary>
        /// <param name="collectionName"></param>
        /// <param name="filePath"></param>
        /// <returns></returns>
        Task<bool> IngestLongFileAsync(string collectionName, string filePath);



        /// <summary>
        /// Search File by ash
        /// </summary>
        /// <param name="collectionName"></param>
        /// <param name="fileHash"></param>
        /// <returns></returns>
        Task<bool> IsFileAlreadyIndexedAsync(string collectionName, string fileHash);


    }
}
